Fix button alignment
DH-IT-Portal-Development/ethics pull request #353
Opened 2022-06-14 21:04 UTC by Meesch

After some noodling and css tutorials, I think the best option to make the buttons align nicely on all screens is to fit them a grid:

![Screenshot 2022-06-14 at 16 03 00](https://user-images.githubusercontent.com/31687030/173688404-6bee730b-f7c2-417a-a670-d012947ed9dc.png)

Addresses #348

2022-06-16 08:04 UTC, tymees requested changes
The trajectory pages now look fine, but the others now look a bit weird:

![image](https://user-images.githubusercontent.com/7061963/174021094-da5c4ba8-1055-4d20-a517-311a1009c12d.png)

There are two main issues at work here:
1) You've used a 4x1 grid for something that's not always 4 items, thus the browser adds a 'fake' column that takes up the rightmost space
2) By using a grid, all items must take the size it receives from te grid, leading to overly wide buttons

I don't know CSS grid well enough to propose a fix... I do know something that'll work using flexbox ;)

2022-06-17 18:37 UTC, Meesch commented on main/static/main/style.css
> +    padding-bottom: 1rem;
yes, this is to make the buttons look good even when there are multiple lines of text:

<img width="985" alt="Screenshot 2022-06-17 at 13 36 55" src="https://user-images.githubusercontent.com/31687030/174357990-47405161-8a40-428e-a562-09d849c94f9e.png">

2022-06-17 18:40 UTC, Meesch commented
Ok, update: I have made it so that there is now a dynamic number of columns, as requested. Personally, I like the wide buttons that take up the whole bottom, even in the extreme cases of two or even just one button:
<img width="988" alt="Screenshot 2022-06-17 at 13 39 14" src="https://user-images.githubusercontent.com/31687030/174358508-e7cf132b-493d-463b-bcb5-abdddcea40d5.png">

<img width="987" alt="Screenshot 2022-06-17 at 13 39 37" src="https://user-images.githubusercontent.com/31687030/174358528-7528539c-1d8b-43a3-8b86-65e10c178234.png">

But I realise this is a matter of taste and possibly convention, so I will defer to your judgement. Let me know what you want to do and I will do it!

2022-06-28 07:36 UTC, tymees commented on main/static/main/style.css
> +    /* grid-auto-columns: min-content; */
This commented out line should be removed

2022-06-28 07:37 UTC, tymees approved these changes
If you remove that commented out line I think it should be fine to merge. 

> But I realise this is a matter of taste and possibly convention, so I will defer to your judgement. Let me know what you want to do and I will do it!

Personally, I don't like that style at all :P

But, it's now consistant across the app and working, so  ¯\\_(ツ)_/¯

2022-07-05 11:45 UTC, merged