Feature/special details
DH-IT-Portal-Development/ethics pull request #425
Opened 2022-10-25 23:55 UTC by Meesch

Addresses issue #420 (nice). I did finish this while pretty stuffed with snot, so you might spot some inaccuracies. One thing I was not able to solve was the fact that the help text for has_special_details (in ```study/models.py```) is not picked up by makemessages -a, so it's not translated.... Any idea what's up with that?

2022-10-25 23:56 UTC, Meesch commented
(also I did a dumb and split this branch off of the hierarchy_fields branch, so it has some commits from that branch that I had to re-commit)

2022-11-21 14:08 UTC, tymees commented
Hm, something seems to have borked migrations wise....

> Creating test database for alias 'default'...
CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0024_alter_study_has_traits, 0024_auto_20221018_1653 in studies).
Proceeding without LDAP settings
To fix them run 'python manage.py makemigrations --merge'
Error: Process completed with exit code 1.

Looks like there are two migrations ``0024``

2022-12-08 15:08 UTC, miggol requested changes
Good work on this PR, even though there are still quite a few rough edges. Besides my inline comments I have these general comments as well:

1. The compare page templates need new fields and field logic
2. Now that `traits` are specific to personal _information_, I think the `verbose_name` _"Select the special characteristics of your participants:"_ is a bit confusing. I guess it still makes sense, but maybe we could change that to _"Please specify the kinds of health information you intend to collect:"_ and then rephrase the trait descriptions.

2022-12-23 11:49 UTC, Meesch commented on studies/templates/studies/study_form.html
> +    check_field_required('special_details', 'medical_traits', 'traits', 'studies', 'SpecialDetail');
I updated the logic in form_styling.html to make this work

2022-12-23 12:09 UTC, Meesch commented
Alright, I think I addressed all your comments @miggol. Do please let me know what you think of the dependency logic and whether there are other things I have not yet addressed.

2023-01-05 12:53 UTC, Meesch commented
Okay, update for the time being: the logic for the field dependencies has been updated, but it glitches if the user changes several fields too quickly after one another. If you wait 4 seconds between toggles of fields, there is no issue, but if you do not, the dependent field will appear and then immediately disappear again. Any insight on why this happens is appreciated, at this point I am ready to rewrite all the dependency logic to solve this.

2023-01-16 13:52 UTC, tymees commented on proposals/templatetags/proposal_filters.py
> +            break
Better to just return True here, it's a bit cleaner

```python
@register.filter
def medical_traits(selected_values, field='medical_traits'):
    for sv in selected_values:
        if getattr(sv, field):
            return True

    return False

2023-01-16 14:03 UTC, tymees commented
> Okay, update for the time being: the logic for the field dependencies has been updated, but it glitches if the user changes several fields too quickly after one another. If you wait 4 seconds between toggles of fields, there is no issue, but if you do not, the dependent field will appear and then immediately disappear again. Any insight on why this happens is appreciated, at this point I am ready to rewrite all the dependency logic to solve this.

Yes I can provide some insight;

There are 2 problems working here, both related to code speed.

The first:
The dependency checks using jQuery were unnecessarily slow. This was caused by (re-)searching for the relevant elements in the _entire DOM_. For example:

```js
$('input[type=checkbox]').each( //something );
$('input[type=checkbox]').change();
```
This will do the search for all checkboxes on the page _twice_, which is slow. 
```js
let checkboxes = $('input[type=checkbox]');
checkboxes.each( //something );
checkboxes.change();
```
This will do it once, taking half the time.

As you can guess, this causes some of the problems, as sometimes the checks were taking longer than the speed of the user's clicks.

I've pushed a commit which not only removes the duplicate searches, it also limits the searches where possible to part of the DOM. (Mostly when searching for the checkboxes, which is now limited to the `ul` element that contains them.) This makes the entire process much more speedy. It's still possible to get the problems as before, but it should be way harder.

The second:
This one is similar, but also different, to the first. ``check_field_required`` does a POST request and resolves it asynchronously. This means the JS is unblocked while waiting for the server's response, allowing changes that might invalidate the post request that's being done. Thus, throwing the page into an invalid state. 

I didn't resolve this issue, as I'm unsure on how to tackle that problem right now.

2023-01-17 14:16 UTC, Meesch commented
> > Okay, update for the time being: the logic for the field dependencies has been updated, but it glitches if the user changes several fields too quickly after one another. If you wait 4 seconds between toggles of fields, there is no issue, but if you do not, the dependent field will appear and then immediately disappear again. Any insight on why this happens is appreciated, at this point I am ready to rewrite all the dependency logic to solve this.
> 
> Yes I can provide some insight;
> 
> There are 2 problems working here, both related to code speed.
> 
> The first: The dependency checks using jQuery were unnecessarily slow. This was caused by (re-)searching for the relevant elements in the _entire DOM_. For example:
> 
> ```js
> $('input[type=checkbox]').each( //something );
> $('input[type=checkbox]').change();
> ```
> 
> This will do the search for all checkboxes on the page _twice_, which is slow.
> 
> ```js
> let checkboxes = $('input[type=checkbox]');
> checkboxes.each( //something );
> checkboxes.change();
> ```
> 
> This will do it once, taking half the time.
> 
> As you can guess, this causes some of the problems, as sometimes the checks were taking longer than the speed of the user's clicks.
> 
> I've pushed a commit which not only removes the duplicate searches, it also limits the searches where possible to part of the DOM. (Mostly when searching for the checkboxes, which is now limited to the `ul` element that contains them.) This makes the entire process much more speedy. It's still possible to get the problems as before, but it should be way harder.
> 
> The second: This one is similar, but also different, to the first. `check_field_required` does a POST request and resolves it asynchronously. This means the JS is unblocked while waiting for the server's response, allowing changes that might invalidate the post request that's being done. Thus, throwing the page into an invalid state.
> 
> I didn't resolve this issue, as I'm unsure on how to tackle that problem right now.

Nice! This is indeed faster and better, thank you for explaining. As for the second issue: I must confess I do not fully understand, but I am happy to hear your in-person explanation of the problem!

2023-01-23 12:19 UTC, miggol approved these changes
I found some missing translations and added them right away. This is now ready for merge as far as I'm concerned. Thanks @tymees for chipping in on the JS side of things.

2023-01-23 12:26 UTC, tymees approved these changes
I've changed the request handling a bit to use a map, so we can keep track of requests for multiple fields at the same time.

Otherwise, a user might still click fast enough to mess up our code. 

I agree that it's mergeable now :)

2023-01-30 14:28 UTC, merged