Serve user uploads with new UserMediaView
DH-IT-Portal-Development/ethics pull request #436
Opened 2022-11-11 16:46 UTC by miggol

This prohibits non-logged-in users from accessing them

2022-11-11 17:30 UTC, tymees requested changes

2022-11-11 17:30 UTC, tymees commented on main/views.py
> +        filepath = os.path.join(settings.MEDIA_ROOT, filename)
As noted in the chat, this is dangerous. An attacker can craft a filename that will result in arbitrary file access on the server. (outside MEDIA_ROOT)

It's not a OMG WE ARE DOOMED scenario, we're still behind a LoginRequiredMixin and Apache seems to be filtering out the more simple malicious filenames, but I still really don't want to rely on those protections alone. Especially as the fix is one if statement ;)

Thus, there should be a check for making sure that the resulting filepath is still inside MEDIA_ROOT.

2022-11-11 17:30 UTC, tymees commented on fetc/urls.py
> +         name='user_upload_2'),
Is this still necessary?

It feels like a fix for uWSGI's static-map, but we are removing that anyways. In addition, we currently don't really control the urls presented to the user, sooooo...

2022-11-11 17:33 UTC, tymees commented on main/views.py
> +        filepath = os.path.join(settings.MEDIA_ROOT, filename)
For those interested, it's called a path traversal attack:
https://owasp.org/www-community/attacks/Path_Traversal

2022-11-11 17:53 UTC, Meesch reviewed
Other than Ty's comment I have tested it locally and everything works as expected!

2022-11-11 17:53 UTC, Meesch commented on main/views.py
> +        try:
```suggestion
if filename in os.listdir(settings.MEDIA_ROOT):  # check if file exists in media root
```

Would this be sufficient sanitization?

2022-11-14 12:24 UTC, tymees approved these changes

2022-11-14 13:28 UTC, merged