Feature/email secretary after decisions
DH-IT-Portal-Development/ethics pull request #582
Opened 2023-11-20 15:54 UTC by EdoStorm96

Some fixes for a two small issues. 

the fix for #581 is pretty self explanatory.

For the issue #563, I updated the `update_go()` of `Review`, as Ty suggested. Please check if this is in the correct spot ... In my testing this works as expected.

Furthermore, I'd appreciate feedback on the text of the e-mail. It's pretty bare bones, but gets the job done, with an overview of all decisions.

PS. I accidentally blacked review_utils.py, but undid it, because it made the diff unreadable.

2023-11-20 16:47 UTC, tymees requested changes
Nice quick turnaround lol :)

Two small errors, otherwise: looks great!

About the email: looks fine; during the meeting we all agreed the contents should not matter that much, the subject is more important.

2023-11-20 16:47 UTC, tymees commented on reviews/utils/review_utils.py
> +    send_mail(subject, msg_plain, settings.EMAIL_FROM, [secretary.email])
As per #563:
> [..] FETC npm (not users!) [..]

Thus, the recipient should be the general fetc email ;)

2023-11-20 16:47 UTC, tymees commented on reviews/utils/review_utils.py
> +    )
You're translating the string, but not adding any translations...

Honestly, as the email is not translated, I'd just drop the `_([..])` tag altogether

2023-11-21 10:34 UTC, miggol requested changes

2023-11-21 10:34 UTC, miggol commented on reviews/utils/review_utils.py
> +    msg_plain = render_to_string("mail/all_decisions_notify.txt", params)
Any translations existing in this input, e.g. `decision.get_go_display`, will render to the currently selected language.

If the user who triggered the `update_go()` happened to be set to English, all translations in here will also turn into English, which is a bit weird. 

See `proposal_utils.notify_local_staff()` for an example of how we manually activate a language for email sending, and then reset it afterwards.

2023-11-21 15:29 UTC, tymees requested changes
One tiny tweak left, and then it's GTG

You don't have to re-request review from me if you fix that tiny detail

2023-11-21 15:29 UTC, tymees commented on reviews/utils/review_utils.py
> +
I should've clarified; you should use `settings.EMAIL_FROM` as the recipient.

It's kinda weird, I know, but `EMAIL_FROM` is the NPM email. Hardcoding this is a bad idea, as names (and thus, emails) in the UU tend to change. It's better if we only have to change the one value when that happens

2023-11-23 09:35 UTC, merged