Fix/improve forms UI
DH-IT-Portal-Development/ethics pull request #687
Opened 2024-08-22 08:20 UTC by EdoStorm96

Here is a mishmash of different small issues. Mostly to do with improving error displays, and general UI improvements for the forms, mostly around sessions and tasks ...

I also found out the non-field-errors were not caught by validation, so I added a small fix for this.

2024-08-27 13:09 UTC, miggol requested changes
Sorry this took so long, I keep ending up diving super deep into the code in these reviews and then don't finish them.

Nice improvements in general.

2024-09-03 11:59 UTC, EdoStorm96 commented on tasks/templates/tasks/task_list.html
> +        {% trans "Deze sessie bevat nog geen taken. Tijd om er één aan te maken!" %}
I was thinking we create a seperate issue for translation ... Because a lot of stuff is not translated or not up to date ...

2024-09-03 12:49 UTC, EdoStorm96 commented
Ok, So I've adressed your comments, and I also found some bugs, which I fixed along the way. 

I noticed that StudyEndForm was missing from the validation, so I've added that. (I see now that I put the wrong commit message regarding this ... oh well.) -> 9899ca7

I found a bug in this form. It was, unnecessarily receiving a study kwarg, this is now fixed.

And I tried to work on StudyDesignForm, and made some changes that will hopefully make this form easier to validate externally. However, as I showed, I did run into a really strang bug, where this form does not get properly initialized in the validator. Its clean method does not get called, and I cannot figure out why this is. I would really appreciate if you could have a look at this, because it is driving me crazy!

2024-09-03 13:39 UTC, miggol approved these changes
Approving, assuming that the study kwarg comment gets fixed. The orthography issue is of course minor

2024-09-03 13:39 UTC, miggol commented on studies/forms.py
> +                _("Je dient minstens één van de opties te selecteren."), code="required"
I recently learned (guess from who) that you're not supposed to write "één" in Dutch if there's no chance of ambiguity. Same with  "Tijd om er één aan te maken!", by the book it shouldn't have accents.

2024-09-03 13:39 UTC, miggol commented on studies/forms.py
> -        self.study = kwargs.pop("study", None)
This View is still getting a `study` kwarg argument from somewhere, causing it to error out.

2024-09-04 12:27 UTC, merged